dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_intall:
  - pip install pip --upgrade
install:
  - pip install gitpython
  - pip install ansible-lint
script:
  pytest test/*.py
